#!/bin/bash

# Helper script used to generate 
# - assets/item_ids.txt
# Args: path to directory containing files generated by ao-id-extractor
# Usage python scripts/generate_assets.sh ${EXTRACTED}


declare game_data_dir="$1"

if [[ -z $game_data_dir ]]; then
    echo "First argument should point to game data dir generated by ao-id-extractor"
    exit 1
fi

declare items_file="$(find $game_data_dir -type f -name items.xml)"

if [[ -z $items_file ]]; then
    echo "$game_data_dir does not contains items.xml file"
    exit 1
fi

echo "Generating assets/item_ids.txt..."
python scripts/item_id.py $items_file > assets/item_ids.txt