name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
  build-win:
    runs-on: windows-latest
    env:
        RUST_TEST_THREADS: 1
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install dependencies
      run: |
              Invoke-WebRequest -UseBasicParsing https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip -OutFile "${Env:TEMP}\wpd.zip"
              Expand-Archive -LiteralPath "${Env:TEMP}\wpd.zip" -DestinationPath "${Env:TEMP}\wpd"
              Move-Item -LiteralPath "${Env:TEMP}\wpd\WpdPack\Lib" -Destination lib
    
    - name: Build
      run: cargo build --verbose
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
              toolchain: stable
              override: true
        - uses: katyo/publish-crates@v1
          with:
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
